### ISSUE TITLE
Currently in use

### ISSUE THREAD

**Issue by cschuber** [freebsd/fcp#19]
I use fxp, dc and xl. My firewall has all three installed.

**Comment by kev009** [comment]
ne and pcn are both emulation targets for i.e qemu, might want to keep them as well for that reason.

On one hand I couldn't justify supporting most of these cards myself and the lifecycle of 12.x gives users a good long while to migrate to remaining supported cards or a legacy friendly OS like NetBSD.  On the other, these drivers are all quite slim (a few thousand lines) and mostly written to the API w/o HALs and much other icky like we see in 10G+ drivers.  I guess it would help to expand the justification aside from the fact that 10/100 is legacy, for instance if we are going to push toward ifnet changes or iflib that would be a great justification to communicate.

**Comment by cschuber** [comment]
The list also includes a gigabit NIC (nfe). Not sure why.

**Comment by brooksdavis** [comment]
fxp, dc and xl are already excluded.  Including nfe was an error that I'll fix.

**Comment by brooksdavis** [comment]
I don't think we need (or want) to support every nic emulated by qemu.  I'd remove `le` in a heartbeat despite it being the default qemu nic if we could attach to e1000 or virtio on mips.

**Comment by brooksdavis** [comment]
Every NIC adds drag any time you touch generic network management infrastructure.  I've had to edit every single driver more that once in the past year.  I'll add some text to this effect.

**Comment by bsdimp** [comment]
Nit: ne is really ed. But you no longer need that with qemu like you did in days of yore. I believe all of virtualbox, fusion vmware (just checked) etc either use real virtio or use an intel nic of some flavor.

**Comment by bsdimp** [comment]
I agree with Brooks: making an exception for a couple is fine, but the more exceptions we make, the less benefit there is. We need to make the tradeoff between 'there's this one old laptop I have that has this' that nobody else has, versus 'there's lots of people still using this hardware' Having numbers would be helpful. In the general discussion, I'd suggest that we set the threshold at 10: "I have 10 machines using XXX on 12.0 today" or 10 people saying the same for one machine.
